apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmq-deployment
  labels:
    app: vprormq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vprormq
  template:
    metadata:
      name: vprormq-pod
      labels:
        app: vprormq
    spec:
      containers:
        - name: vprormq-container
          image: rabbitmq
          ports:
            - name: vprormq-port
              containerPort: 5672
          env:
            - name: RABBITMQ_DEFAULT_PASS
              valueForm:
                secretKeyRef:
                  name: app-secret
                  key: rmq-pass
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: rmq-usr
